#ifndef UE4SS_SDK_ABP_HydroGuy_HPP
#define UE4SS_SDK_ABP_HydroGuy_HPP

class UABP_HydroGuy_C : public UAnimInstance
{
    FPointerToUberGraphFrame UberGraphFrame;                                          // 0x02C0 (size: 0x8)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_5;                          // 0x02C8 (size: 0x158)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_38;                     // 0x0420 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_37;                     // 0x0448 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_36;                     // 0x0470 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_28;                         // 0x0498 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_28;                               // 0x0518 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_35;                     // 0x0548 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_34;                     // 0x0570 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_33;                     // 0x0598 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_32;                     // 0x05C0 (size: 0x28)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_9;                      // 0x05E8 (size: 0xE8)
    FAnimNode_StateResult AnimGraphNode_StateResult_27;                               // 0x06D0 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_31;                     // 0x0700 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_30;                     // 0x0728 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_29;                     // 0x0750 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_28;                     // 0x0778 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_27;                     // 0x07A0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_26;                     // 0x07C8 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_27;                         // 0x07F0 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_26;                               // 0x0870 (size: 0x30)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_26;                         // 0x08A0 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_25;                               // 0x0920 (size: 0x30)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_25;                         // 0x0950 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_24;                               // 0x09D0 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_9;                              // 0x0A00 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_23;                               // 0x0AB0 (size: 0x30)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_24;                         // 0x0AE0 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_22;                               // 0x0B60 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_8;                              // 0x0B90 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_21;                               // 0x0C40 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_25;                     // 0x0C70 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_24;                     // 0x0C98 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_23;                     // 0x0CC0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_22;                     // 0x0CE8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_21;                     // 0x0D10 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_23;                         // 0x0D38 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_20;                               // 0x0DB8 (size: 0x30)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_22;                         // 0x0DE8 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_19;                               // 0x0E68 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_7;                              // 0x0E98 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_18;                               // 0x0F48 (size: 0x30)
    FAnimNode_TwoWayBlend AnimGraphNode_TwoWayBlend;                                  // 0x0F78 (size: 0xC8)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_8;                      // 0x1040 (size: 0xE8)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_7;                      // 0x1128 (size: 0xE8)
    FAnimNode_StateResult AnimGraphNode_StateResult_17;                               // 0x1210 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_20;                     // 0x1240 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_19;                     // 0x1268 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_18;                     // 0x1290 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_17;                     // 0x12B8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_16;                     // 0x12E0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_15;                     // 0x1308 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_21;                         // 0x1330 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_16;                               // 0x13B0 (size: 0x30)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_20;                         // 0x13E0 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_15;                               // 0x1460 (size: 0x30)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_19;                         // 0x1490 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_14;                               // 0x1510 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_6;                              // 0x1540 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_13;                               // 0x15F0 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_5;                              // 0x1620 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_12;                               // 0x16D0 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_4;                              // 0x1700 (size: 0xB0)
    FAnimNode_Inertialization AnimGraphNode_Inertialization;                          // 0x17B0 (size: 0x70)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_14;                     // 0x1820 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_13;                     // 0x1848 (size: 0x28)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_6;                      // 0x1870 (size: 0xE8)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_5;                            // 0x1958 (size: 0xC8)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_5;                      // 0x1A20 (size: 0xE8)
    FAnimNode_StateResult AnimGraphNode_StateResult_11;                               // 0x1B08 (size: 0x30)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_18;                         // 0x1B38 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_10;                               // 0x1BB8 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_3;                              // 0x1BE8 (size: 0xB0)
    FAnimNode_Slot AnimGraphNode_Slot_2;                                              // 0x1C98 (size: 0x48)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_4;                          // 0x1CE0 (size: 0x158)
    FAnimNode_ApplyMeshSpaceAdditive AnimGraphNode_ApplyMeshSpaceAdditive_3;          // 0x1E38 (size: 0xD0)
    FAnimNode_Slot AnimGraphNode_Slot_1;                                              // 0x1F08 (size: 0x48)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_4;                        // 0x1F50 (size: 0xA0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_13;                           // 0x1FF0 (size: 0x28)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_3;                      // 0x2018 (size: 0xC0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_12;                           // 0x20D8 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_17;                         // 0x2100 (size: 0x80)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_3;                          // 0x2180 (size: 0x158)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_11;                           // 0x22D8 (size: 0x28)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_4;                            // 0x2300 (size: 0xC8)
    FAnimNode_Slot AnimGraphNode_Slot;                                                // 0x23C8 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_16;                         // 0x2410 (size: 0x80)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_3;                            // 0x2490 (size: 0xC8)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_15;                         // 0x2558 (size: 0x80)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_2;                      // 0x25D8 (size: 0xC0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_10;                           // 0x2698 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_14;                         // 0x26C0 (size: 0x80)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_1;                      // 0x2740 (size: 0xC0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_9;                            // 0x2800 (size: 0x28)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_4;                      // 0x2828 (size: 0xE8)
    FAnimNode_Fabrik AnimGraphNode_Fabrik_1;                                          // 0x2910 (size: 0x190)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_3;     // 0x2AA0 (size: 0x20)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_3;     // 0x2AC0 (size: 0x20)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_2;                          // 0x2AE0 (size: 0x158)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_8;                            // 0x2C38 (size: 0x28)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_3;                        // 0x2C60 (size: 0xA0)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_21;                                 // 0x2D00 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_20;                                 // 0x2E08 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_19;                                 // 0x2F10 (size: 0x108)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_2;     // 0x3018 (size: 0x20)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_18;                                 // 0x3038 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_17;                                 // 0x3140 (size: 0x108)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_2;     // 0x3248 (size: 0x20)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_7;                            // 0x3268 (size: 0x28)
    FAnimNode_TwoBoneIK AnimGraphNode_TwoBoneIK_1;                                    // 0x3290 (size: 0x1E0)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;     // 0x3470 (size: 0x20)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;     // 0x3490 (size: 0x20)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_16;                                 // 0x34B0 (size: 0x108)
    FAnimNode_TwoBoneIK AnimGraphNode_TwoBoneIK;                                      // 0x35C0 (size: 0x1E0)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_2;                            // 0x37A0 (size: 0xC8)
    FAnimNode_RandomPlayer AnimGraphNode_RandomPlayer;                                // 0x3868 (size: 0x78)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_1;                          // 0x38E0 (size: 0x158)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_6;                            // 0x3A38 (size: 0x28)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_15;                                 // 0x3A60 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_14;                                 // 0x3B68 (size: 0x108)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose;                            // 0x3C70 (size: 0x158)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_5;                            // 0x3DC8 (size: 0x28)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_2;                        // 0x3DF0 (size: 0xA0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_4;                            // 0x3E90 (size: 0x28)
    FAnimNode_Fabrik AnimGraphNode_Fabrik;                                            // 0x3EC0 (size: 0x190)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_13;                         // 0x4050 (size: 0x80)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_13;                                 // 0x40D0 (size: 0x108)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;       // 0x41D8 (size: 0x20)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;       // 0x41F8 (size: 0x20)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_12;                                 // 0x4218 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_11;                                 // 0x4320 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_10;                                 // 0x4428 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_9;                                  // 0x4530 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_8;                                  // 0x4638 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_7;                                  // 0x4740 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_6;                                  // 0x4848 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_5;                                  // 0x4950 (size: 0x108)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_12;                         // 0x4A58 (size: 0x80)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum;                          // 0x4AD8 (size: 0xB0)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_11;                         // 0x4B88 (size: 0x80)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_1;                        // 0x4C08 (size: 0xA0)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_3;                      // 0x4CA8 (size: 0xE8)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_12;                     // 0x4D90 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_11;                     // 0x4DB8 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_10;                         // 0x4DE0 (size: 0x80)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_2;                      // 0x4E60 (size: 0xE8)
    FAnimNode_ApplyMeshSpaceAdditive AnimGraphNode_ApplyMeshSpaceAdditive_2;          // 0x4F48 (size: 0xD0)
    FAnimNode_StateResult AnimGraphNode_StateResult_9;                                // 0x5018 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_10;                     // 0x5048 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_9;                      // 0x5070 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_8;                      // 0x5098 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_7;                      // 0x50C0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_6;                      // 0x50E8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_5;                      // 0x5110 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_4;                      // 0x5138 (size: 0x28)
    FAnimNode_ApplyMeshSpaceAdditive AnimGraphNode_ApplyMeshSpaceAdditive_1;          // 0x5160 (size: 0xD0)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_9;                          // 0x5230 (size: 0x80)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_3;                            // 0x52B0 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_8;                                // 0x52D8 (size: 0x30)
    FAnimNode_ApplyMeshSpaceAdditive AnimGraphNode_ApplyMeshSpaceAdditive;            // 0x5308 (size: 0xD0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_2;                            // 0x53D8 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_8;                          // 0x5400 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_7;                                // 0x5480 (size: 0x30)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_3;                      // 0x54B0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_2;                      // 0x54D8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_1;                      // 0x5500 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;                        // 0x5528 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_7;                          // 0x5550 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_6;                                // 0x55D0 (size: 0x30)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_6;                          // 0x5600 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_5;                                // 0x5680 (size: 0x30)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_5;                          // 0x56B0 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_4;                                // 0x5730 (size: 0x30)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_4;                          // 0x5760 (size: 0x80)
    FAnimNode_StateResult AnimGraphNode_StateResult_3;                                // 0x57E0 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_2;                              // 0x5810 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult_2;                                // 0x58C0 (size: 0x30)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_1;                            // 0x58F0 (size: 0x28)
    FAnimNode_StateResult AnimGraphNode_StateResult_1;                                // 0x5918 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_1;                              // 0x5948 (size: 0xB0)
    FAnimNode_StateResult AnimGraphNode_StateResult;                                  // 0x59F8 (size: 0x30)
    FAnimNode_StateMachine AnimGraphNode_StateMachine;                                // 0x5A28 (size: 0xB0)
    FAnimNode_Root AnimGraphNode_Root;                                                // 0x5AD8 (size: 0x30)
    FAnimNode_BlendListByInt AnimGraphNode_BlendListByInt;                            // 0x5B08 (size: 0xA0)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_3;                          // 0x5BA8 (size: 0x80)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend;                        // 0x5C28 (size: 0xC0)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose;                              // 0x5CE8 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_2;                          // 0x5D10 (size: 0x80)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_4;                                  // 0x5D90 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_3;                                  // 0x5E98 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_2;                                  // 0x5FA0 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_1;                                  // 0x60A8 (size: 0x108)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone;                                    // 0x61B0 (size: 0x108)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_1;                          // 0x62B8 (size: 0x80)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_1;                            // 0x6338 (size: 0xC8)
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive;                              // 0x6400 (size: 0xC8)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;                            // 0x64C8 (size: 0x80)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_1;                      // 0x6548 (size: 0xE8)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer;                        // 0x6630 (size: 0xE8)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;                          // 0x6718 (size: 0xA0)
    class ACharacter* Character;                                                      // 0x67B8 (size: 0x8)
    FVector Velocity;                                                                 // 0x67C0 (size: 0xC)
    float Speed;                                                                      // 0x67CC (size: 0x4)
    float Forward;                                                                    // 0x67D0 (size: 0x4)
    float Right;                                                                      // 0x67D4 (size: 0x4)
    float WalkRunAlpha;                                                               // 0x67D8 (size: 0x4)
    float RunSprintAlpha;                                                             // 0x67DC (size: 0x4)
    float MovementAdditiveAlpha;                                                      // 0x67E0 (size: 0x4)
    float DeltaTimeX;                                                                 // 0x67E4 (size: 0x4)
    float WalkPlayRate;                                                               // 0x67E8 (size: 0x4)
    float RunPlayRate;                                                                // 0x67EC (size: 0x4)
    float CrouchPlayRate;                                                             // 0x67F0 (size: 0x4)
    float RotationRate;                                                               // 0x67F4 (size: 0x4)
    float TurnRate;                                                                   // 0x67F8 (size: 0x4)
    bool isMoving?;                                                                   // 0x67FC (size: 0x1)
    bool isSprinting?;                                                                // 0x67FD (size: 0x1)
    bool isCrouched?;                                                                 // 0x67FE (size: 0x1)
    bool isForward?;                                                                  // 0x67FF (size: 0x1)
    bool isRight?;                                                                    // 0x6800 (size: 0x1)
    bool isTurningInPlace?;                                                           // 0x6801 (size: 0x1)
    bool isTurningRight?;                                                             // 0x6802 (size: 0x1)
    bool isTurningLeft?;                                                              // 0x6803 (size: 0x1)
    bool isChangingDirection?;                                                        // 0x6804 (size: 0x1)
    TEnumAsByte<EMovementMode> MovementMode;                                          // 0x6805 (size: 0x1)
    FRotator LastRotation;                                                            // 0x6808 (size: 0xC)
    FVector LastVelocity;                                                             // 0x6814 (size: 0xC)
    class UAnimSequence* Pose;                                                        // 0x6820 (size: 0x8)
    bool HasPose?;                                                                    // 0x6828 (size: 0x1)
    FTimerHandle ClearPoseTimer;                                                      // 0x6830 (size: 0x8)
    TEnumAsByte<E_ItemType::Type> PoseItemType;                                       // 0x6838 (size: 0x1)
    bool IsTwoHanded?;                                                                // 0x6839 (size: 0x1)
    bool UseHandIK?;                                                                  // 0x683A (size: 0x1)
    FRotator SpineRotation;                                                           // 0x683C (size: 0xC)
    FRotator NeckRotation;                                                            // 0x6848 (size: 0xC)
    FVector HandEffectorR;                                                            // 0x6854 (size: 0xC)
    FVector HandEffectorL;                                                            // 0x6860 (size: 0xC)
    FRotator EffectorRotationR;                                                       // 0x686C (size: 0xC)
    FRotator EffectorRotationL;                                                       // 0x6878 (size: 0xC)
    FTimerHandle IK_FootTraceTimer;                                                   // 0x6888 (size: 0x8)
    FVector ActorLoc;                                                                 // 0x6890 (size: 0xC)
    FVector MeshLoc;                                                                  // 0x689C (size: 0xC)
    FVector PelvisLoc;                                                                // 0x68A8 (size: 0xC)
    FVector RightFootLoc;                                                             // 0x68B4 (size: 0xC)
    FVector LeftFootLoc;                                                              // 0x68C0 (size: 0xC)
    float PelvisIK_Offset;                                                            // 0x68CC (size: 0x4)
    bool RightFootIK?;                                                                // 0x68D0 (size: 0x1)
    float FootIK_OffsetR;                                                             // 0x68D4 (size: 0x4)
    float FootIK_OffsetL;                                                             // 0x68D8 (size: 0x4)
    FVector FootEffectorR;                                                            // 0x68DC (size: 0xC)
    FVector FootEffectorL;                                                            // 0x68E8 (size: 0xC)
    FVector PelvisOffset;                                                             // 0x68F4 (size: 0xC)
    FVector FootEffectorR_Interp;                                                     // 0x6900 (size: 0xC)
    FVector FootEffectorL_Interp;                                                     // 0x690C (size: 0xC)
    FVector PelvisOffset_Interp;                                                      // 0x6918 (size: 0xC)
    FVector LegJointTargetR;                                                          // 0x6924 (size: 0xC)
    FVector LegJointTargetL;                                                          // 0x6930 (size: 0xC)
    class ABP_Character_HydroGuy_C* HydroGuyRef;                                      // 0x6940 (size: 0x8)
    FTransform Upper Head Transform;                                                  // 0x6950 (size: 0x30)
    FTransform Lower Head Transform;                                                  // 0x6980 (size: 0x30)
    FTransform Forehead Transform;                                                    // 0x69B0 (size: 0x30)
    FTransform NoseTransform;                                                         // 0x69E0 (size: 0x30)
    FTransform Chin Transform;                                                        // 0x6A10 (size: 0x30)
    FTransform Ear Right Transform;                                                   // 0x6A40 (size: 0x30)
    FTransform Ear Left Transform;                                                    // 0x6A70 (size: 0x30)
    FTransform Eyebrow Right Transform;                                               // 0x6AA0 (size: 0x30)
    FTransform Eyebrow Left Transform;                                                // 0x6AD0 (size: 0x30)
    class UAnimSequence* VehiclePose;                                                 // 0x6B00 (size: 0x8)
    bool HasVehiclePose?;                                                             // 0x6B08 (size: 0x1)
    TEnumAsByte<E_Vehicle::Type> VehicleType;                                         // 0x6B09 (size: 0x1)
    float Steering;                                                                   // 0x6B0C (size: 0x4)
    float FemAlpha;                                                                   // 0x6B10 (size: 0x4)
    float IdleTimeOffset;                                                             // 0x6B14 (size: 0x4)
    int32 PoseMode;                                                                   // 0x6B18 (size: 0x4)
    float PoseBlendTime;                                                              // 0x6B1C (size: 0x4)
    class AActor* TargetActor;                                                        // 0x6B20 (size: 0x8)
    FRotator LookAtRotation;                                                          // 0x6B28 (size: 0xC)
    class ABP_NPC_C* NPC ref;                                                         // 0x6B38 (size: 0x8)
    float SpeakingAlpha;                                                              // 0x6B40 (size: 0x4)
    bool isSpeaking?;                                                                 // 0x6B44 (size: 0x1)
    bool HasBasePose?;                                                                // 0x6B45 (size: 0x1)
    class UAnimSequence* BasePose;                                                    // 0x6B48 (size: 0x8)

    void AnimGraph(FPoseLink& AnimGraph);
    void SetBasePose(class UAnimSequence* BasePose);
    void LookAtActor();
    void SetFaceTransforms();
    void IK_FootTrace(FVector SocketLocation, float& IK_Offset);
    void FootIK_Lerp();
    void FootIK();
    void ClearPose();
    void UpdatePose(class UAnimSequence* NewPose, int32 PoseMode, float PoseBlendTime);
    void MovementCalculations();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_ModifyBone_FA3EBD9C434F2DF6E2DA0284F2577BD6();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_ModifyBone_908D17CA41C5E2CDE9053F828D4995CC();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_ModifyBone_B5905587412CA095EACFD1B385FFBD80();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_ModifyBone_38B281C74CBE0B9F98E84BB65248A3F7();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_ModifyBone_FDFCB01344E576A249CF788C6729103E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_ModifyBone_54ABC4844CB51898CDF2A08123653038();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_ModifyBone_B54CC81E4F08FE1766A4B19409CF420A();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_ModifyBone_1EA18FED466BD2ACC06516937FCD6DB1();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_ModifyBone_0DEAC6A44627464EEFCB5BB321EEE958();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_Fabrik_ADA1A0234DA78094C83642BF0601C0B1();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_ModifyBone_9E39E2314CB252A8BEDFC699DDAD27B8();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_ModifyBone_959A8E534F300656CF97369FF750EE59();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_Fabrik_0BDFDBC64DDE88B804D457BFD5305B48();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_A5D1182549B0ED7126BC22A29C0480C4();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_ACF9651147ACE3D8C18B0F83EBE9555C();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_44EBCB594980E4D87FFA36B3DD4EC37C();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_DAC7E0FA479183308AF8478B9EC6CC6A();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_4C13F4C04DBAEBD38D91D9986549FEE3();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_5D9DB8B7439615877E175DBACEB4727E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_783CF7124E5FB5E0E76183A63A5E0A48();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_D836EF4247CB8C4AAC907ABC1D72AAE8();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_EBBD74FA402B5D10176AB182755EB959();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_AB5E2C3B4FF9BDA91CDEC3ADB7133CA0();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_49A2E1184298A235CC1FCD82D1B8682F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_A432708F4A64AC1FA26210B3C78FDA3D();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_2424749142DC47D42B6BAFA811D9E62B();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_F605B9FD44212BDD7A260D8C7B8A04AA();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_57264BAB465DBE44CE1C4EA9B633BD4F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_HydroGuy_AnimGraphNode_TransitionResult_0FB21F1A4E7A1CE7DE9B7186D790DE2A();
    void BlueprintUpdateAnimation(float DeltaTimeX);
    void BlueprintInitializeAnimation();
    void ExecuteUbergraph_ABP_HydroGuy(int32 EntryPoint);
}; // Size: 0x6B50

#endif
