#ifndef UE4SS_SDK_BP_GameController_HPP
#define UE4SS_SDK_BP_GameController_HPP

class ABP_GameController_C : public APlayerController
{
    FPointerToUberGraphFrame UberGraphFrame;
    float MoveTimeline_NewTrack_0_637096C0404CFE678CE754B416A1F939;
    TEnumAsByte<ETimelineDirection::Type> MoveTimeline__Direction_637096C0404CFE678CE754B416A1F939;
    class UTimelineComponent* MoveTimeline;
    class UUI_HUD_C* HUD;
    TEnumAsByte<E_Crosshairs::Type> CurrentCrosshair;
    class ABP_HydroVoxelWorld_C* VoxelWorld;
    class ABP_GameCharacter_C* Game Character;
    class ABP_ParentItem_C* CarryingItem;
    bool InStore?;
    class ABP_ParentItem_C* PlacingItem;
    float BuildingZRotation;
    float BuildingLength;
    class AActor* LastThingLookingAt;
    float BuildingXRotation;
    class UUserWidget* OpenUI;
    FTransform MenuLocation;
    FTransform Player1Location;
    FTimerHandle AutoSaverHandle;
    class ABP_DayNightCycle_C* DayNight;
    class AActor* CurrentVehicle;
    TEnumAsByte<E_MovementMode::Type> CurrentMovementMode;
    float Building YRotation;
    class UAudioComponent* Soundtrack;
    float BuildingLengthOffset;
    FDateTime StartingUTC;
    bool AutosaveToggle;
    TArray<class UObject*> HighlightedObjects;
    class ABP_ScreenshotCam_C* ScreenshotCam;
    class UUI_ScreenshotCam_C* ScreenshotCamUI;
    float TimeBeforeScreenshotCam;
    FTransform StartingTrans;
    FTransform TargetTrans;
    float PickupTimerLerp;
    float PlayerVoicePitch;
    class ABP_ParentVehicle_C* NearestVehicle;
    FS_DoubleVec PreviousPlacementLocRot;
    FTransform Player2Location;
    FTransform Player3Location;
    FTransform Player4Location;
    FTimerHandle PickupLerpTimerHandle;
    FTimerHandle MenuFocusTimer;
    class ABP_Dummy_HydroGuy_C* Dummy;
    bool IsCreativeMode?;
    bool IsCloudSave?;
    FString PlayerName;
    bool RotationModify;
    bool HardHatMode?;
    class UUI_Menu_Loading_C* LoadingToolTip;

    void ComponentsToSave(TArray<class UActorComponent*>& Components);
    FVoxelIntBox GetBoxBoundsInVoxel(class AVoxelWorld* VoxelWorld, FVector Location, float Bounds);
    void Scan for Items in Voxel Dirt(FVector Location, float Rad);
    void HardHatCheck();
    void UnhighlightCleanup();
    FTransform FindSpawnTransform();
    void DeleteSaveFile(FString SaveSlot);
    FString FormatCloudPathToLocalPath(FString SourceString);
    void FormatSaveSlotCloudPath(FString SaveSlot, FString FilePath, FString& CloudPath);
    void GetFileDataFromCloud(FString CloudFilePath, FString LocalFilePath, bool& Conflict?, TArray<uint8>& Data);
    bool IsMainController?();
    void PropagateCloudSaves();
    void GetSaveSlotFiles(FString SaveSlot, TArray<FString>& Files);
    FString GetSaveSlotDirectory(FString SaveSlot);
    FString GetSaveDirectory();
    void LoadCurrentFilesFromCloud(bool Override?, bool& Conflict?, FText& CloudTime, FText& LocalTime);
    void WriteCurrentFilesToCloud();
    void MenuFocusTick();
    void ToggleMenuFocusTimer(bool On?);
    void ScanForItemsOnTop(FVector Location, float ExtentX, float ExtentY);
    void SetHUD_Crosshair(TEnumAsByte<E_Crosshairs::Type> Crosshair);
    void BoxTraceForRelics(FVector Location);
    void SetStartPosition();
    void MoveVehicleToNearestUnstickPoint();
    void Hrrm();
    void InitController();
    void PlayerIsThief(class ABP_WorldStore_C* Store);
    void Spawn Store Item(class ABP_ParentItem_C* Item);
    void ChangeBuildRotation(int32 XYZ?);
    void TryPickupItem();
    bool LineTraceFromCharacter(FHitResult& OutHit);
    void StartFreeplacing();
    void DeniedDrop();
    void PickUpItem(class ABP_ParentItem_C* Item);
    void SpawnMusic();
    void RecallVehicle();
    void RemoveDirtVehicle(FVector Location1, FVector Location2);
    void CameraShake(TEnumAsByte<E_CameraShakes::Type> Type);
    void RemoveDirtLine(FVector Position, float Radius);
    void ExitVehicle(class AActor* Vehicle);
    void EnterNewVehicle(class AActor* Vehicle);
    void UnhighlightObject();
    void HighlightObject(class AActor* Actor);
    void TryHighlightObject(const FHitResult& Hit, bool& Result);
    void SpawnInitialItems();
    void MovePlayerToNearestUnstickPoint();
    void PostOpenUI(class UUserWidget* OpenUI);
    void CloseAllUI();
    void DropItem(bool& TrueDrop);
    void PositionItemTimer();
    void CrosshairTrace();
    void MoveTimeline__FinishedFunc();
    void MoveTimeline__UpdateFunc();
    void InpActEvt_MouseScrollDown_K2Node_InputKeyEvent_2(FKey Key);
    void InpActEvt_Rotate_K2Node_InputActionEvent_13(FKey Key);
    void InpActEvt_Rotate2_K2Node_InputActionEvent_12(FKey Key);
    void InpActEvt_Pickup_K2Node_InputActionEvent_11(FKey Key);
    void InpActEvt_Pickup_K2Node_InputActionEvent_10(FKey Key);
    void InpActEvt_VehicleKey_K2Node_InputActionEvent_9(FKey Key);
    void InpActEvt_MouseScrollUp_K2Node_InputKeyEvent_1(FKey Key);
    void InpActEvt_Rotate3_K2Node_InputActionEvent_8(FKey Key);
    void InpActEvt_Wiki_K2Node_InputActionEvent_7(FKey Key);
    void InpActEvt_RMB_K2Node_InputActionEvent_6(FKey Key);
    void InpActEvt_RMB_K2Node_InputActionEvent_5(FKey Key);
    void OnCompleted_9EE0ABC14602C7545F03D1AF77EC46FC();
    void InpActEvt_LMB_K2Node_InputActionEvent_4(FKey Key);
    void InpActEvt_LMB_K2Node_InputActionEvent_3(FKey Key);
    void InpActEvt_AnyKey_K2Node_InputKeyEvent_0(FKey Key);
    void InpActEvt_EscMenu_K2Node_InputActionEvent_2(FKey Key);
    void InpActEvt_RotationMod_K2Node_InputActionEvent_1(FKey Key);
    void InpActEvt_RotationMod_K2Node_InputActionEvent_0(FKey Key);
    void MoveDirt(bool PickUp?, float Radius);
    void FreePlayer();
    void autosave();
    void LevelTerrain(FVoxelIntBox Remove, FVoxelIntBox Add);
    void RemoveDirtByLocation(FVector Location, float Radius);
    void VehicleRemoveDirt(FVector Location1, FVector Location2);
    void HudAlertDropped();
    void NoLongerPlacingItem();
    void PlaceDownItem();
    void PositioningItem(class ABP_ParentItem_C* Item);
    void ToggleScreenshotCam();
    void ChangeTime(float Amount, bool GrowCrops?);
    void TogglePauseTime();
    void LerpToCharacter(class ABP_ParentItem_C* Item, class USceneComponent* Socket Component);
    void PickupLerpTimer();
    void EMS Save();
    void StartAutosaverTimer(float Time);
    void ReceiveTick(float DeltaSeconds);
    void StartGameLerp();
    void ReceiveBeginPlay();
    void ActorPreSave();
    void ActorSaved();
    void ReceivePossess(class APawn* PossessedPawn);
    void ReceiveUnPossess(class APawn* UnpossessedPawn);
    void SaveToCloud();
    void SensitivityChanged(float NewValue);
    void ReceiveDestroyed();
    void InpAxisEvt_MouseRight_K2Node_InputAxisEvent_0(float AxisValue);
    void ActorLoaded();
    void AutosaveChanged(float NewValue);
    void ExecuteUbergraph_BP_GameController(int32 EntryPoint);
};

#endif
