#ifndef UE4SS_SDK_UI_EscMenu_HPP
#define UE4SS_SDK_UI_EscMenu_HPP

class UUI_EscMenu_C : public UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* SlapUpConfirmMainMenu;
    class UWidgetAnimation* SlapUpConfirmDesktop;
    class UWidgetAnimation* SlapUpConfirmClear;
    class UH_ButtonMetal3_C* CancelClearButton;
    class UCanvasPanel* CanvasPanel_RemotePlay;
    class UH_ButtonMetal1_C* ClearConfirmButton;
    class UH_ButtonWood1_C* ClearDirtChunks;
    class UH_ButtonWood3_C* ClearRawResources;
    class UCanvasPanel* ConfirmClearCanvas;
    class UH_TextSubTitle_C* ConfirmClearText;
    class UCanvasPanel* ConfirmDesktop;
    class UHSmallButton2_C* DesktopButton;
    class UH_ButtonMetal2_C* DesktopCancelButton;
    class UH_ButtonMetal3_C* DesktopConfirmButton;
    class UButton* DiscordButton;
    class UImage* EscMenu_Footer;
    class UImage* EscMenu_Header;
    class UH_Background400x200_C* H_Background400x200_C_0;
    class UH_Background400x200_C* H_Background400x200_C_1;
    class UH_Background400x200_C* H_Background400x200_C_2;
    class UH_ButtonWood3_C* H_ButtonWood3_UnstuckP2;
    class UH_ButtonWood3_C* H_ButtonWood3_UnstuckP3;
    class UH_ButtonWood3_C* H_ButtonWood3_UnstuckP4;
    class UH_Midground300x70_C* H_Midground300x70_C_0;
    class UH_TextSubTitle_C* H_TextSubTitle_Instructions;
    class UHCheckbox_C* HCheckbox_Player1Gamepad;
    class UHorizontalBox* HorizontalBox_UnstuckSplitscreen;
    class UImage* Image_132;
    class UImage* Image_controllerconfig;
    class UImage* Image_kbmcontroller;
    class UButton* InstagramButton;
    class UCanvasPanel* MainCanvas;
    class UHSmallButton2_C* MainMenuButton;
    class UH_ButtonMetal3_C* MainMenuCancelButton;
    class UH_ButtonMetal2_C* MainMenuConfirmButton;
    class UImage* QuickActionFooter-SocialsBG;
    class UImage* QuickActionHeader;
    class UH_ButtonWood2_C* RecallButton;
    class UHSmallButton1_C* ReturnButton;
    class UCanvasPanel* ReturnMainMenuCanvas;
    class UHSmallButton1_C* SaveButton;
    class UH_TextTitle_C* SaveReturnToMenuText;
    class UHSmallButton1_C* ScreenshotCameraButton;
    class UHSmallButton1_C* SettingsButton;
    class USizeBox* SizeBox_UnstuckP2;
    class USizeBox* SizeBox_UnstuckP3;
    class USizeBox* SizeBox_UnstuckP4;
    class UButton* TikTokButton;
    class UButton* TwitterButton_1;
    class UH_ButtonWood1_C* UnstuckButton;
    class UWidgetSwitcher* WidgetSwitcher_remoteplayconfig;
    class UButton* WikiButton_1;
    class UButton* YTButton_1;
    class UObject* SettingsMenu;
    bool ClearDirt?;
    bool Tutorial?;

    ESlateVisibility Get_CanvasPanel_RemotePlay_Visibility_0();
    void ConfigureRemotePlayMenu(bool P1Controller?);
    void SetUnstuckSplitscreenVisibility();
    void UnstuckPlayer(int32 PlayerIndex);
    void OnCompleted_E672DCBE4C9A6FF7427E0FB1F8B565BF();
    void OnCompleted_B320C3EA4954BDB22F95C5AE19682279();
    void BndEvt__ReturnButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UnstuckButton_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature();
    void BndEvt__MainMenuButton_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__MainMenuCancelButton_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__MainMenuConfirmButton_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__RecallButton_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SaveButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SettingsButton_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ScreenshotCameraButton_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ClearConfirmButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__CancelClearButton_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ClearRawResources_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ClearDirtChunks_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_EscMenu_DesktopButton_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_EscMenu_DesktopCancelButton_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_EscMenu_DesktopConfirmButton_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature();
    void Construct();
    void BndEvt__UI_EscMenu_HCheckbox_C_176_K2Node_ComponentBoundEvent_21_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
    void BndEvt__UI_EscMenu_H_ButtonWood3_UnstuckP2_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_EscMenu_H_ButtonWood3_UnstuckP3_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_EscMenu_H_ButtonWood3_UnstuckP4_K2Node_ComponentBoundEvent_24_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_EscMenu_TwitterButton_1_K2Node_ComponentBoundEvent_25_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_EscMenu_WikiButton_1_K2Node_ComponentBoundEvent_26_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_EscMenu_YTButton_1_K2Node_ComponentBoundEvent_27_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_EscMenu_TikTokButton_K2Node_ComponentBoundEvent_28_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_EscMenu_InstagramButton_K2Node_ComponentBoundEvent_29_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_EscMenu_DiscordButton_K2Node_ComponentBoundEvent_30_OnButtonClickedEvent__DelegateSignature();
    void Destruct();
    void ExecuteUbergraph_UI_EscMenu(int32 EntryPoint);
};

#endif
