#ifndef UE4SS_SDK_UI_MainMenu_HPP
#define UE4SS_SDK_UI_MainMenu_HPP

class UUI_MainMenu_C : public UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UButton* ARButton;
    class UH_ButtonMetal1_C* CancelQuitButton;
    class UCanvasPanel* ConfirmQuitPanel;
    class UButton* CreditsButton;
    class UCanvasPanel* CustomizationPanel;
    class UButton* CZButton;
    class UButton* DAButton;
    class UButton* DEButton;
    class UButton* DiscordButton;
    class UButton* ESButton;
    class UButton* FRButton;
    class UH_Background500x350_C* H_Background500x350_C_0;
    class UH_Midground400x100_C* H_Midground400x100_C_0;
    class UImage* Image_91;
    class UButton* InstagramButton;
    class UButton* ItButton;
    class UButton* JAButton;
    class UButton* KOButton;
    class UButton* MerchButton;
    class UButton* ModsButton;
    class UButton* NewGameButton;
    class UButton* NLButton;
    class UButton* NOButton;
    class UButton* PatchNotesButton;
    class UButton* PirateButton;
    class UButton* PLButton;
    class UButton* PTButton;
    class UH_ButtonMetal1_C* QuitConfirmButton;
    class UButton* QuitPanelButton;
    class UButton* RoButton;
    class UButton* RUButton;
    class UButton* SaveManagerButton;
    class UButton* SettingsPanelButton;
    class UButton* SVButton;
    class UButton* TikTokButton;
    class UButton* TRButton;
    class UButton* TutorialButton;
    class UButton* TWButton;
    class UButton* TwitterButton;
    class UUI_CustomizationMenu_C* UI_CustomizationMenu;
    class UUI_PlayerShelf_C* UI_PlayerShelf;
    class UButton* UKButton;
    class UButton* WikiButton;
    class UButton* YTButton;
    class UButton* ZHButton;
    class UUserWidget* OpenWidget;
    class UWidget* OpenPanel;

    void OpenPersistentWidget(class UWidget* Widget);
    void CloseUI();
    void OpenSpawnedWidget(class UUserWidget* Widget);
    void BndEvt__UKButton_K2Node_ComponentBoundEvent_36_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__RUButton_K2Node_ComponentBoundEvent_37_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__PirateButton_K2Node_ComponentBoundEvent_38_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__PTButton_K2Node_ComponentBoundEvent_39_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__DEButton_K2Node_ComponentBoundEvent_40_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__FRButton_K2Node_ComponentBoundEvent_41_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__TRButton_K2Node_ComponentBoundEvent_42_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__NLButton_K2Node_ComponentBoundEvent_50_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__PLButton_K2Node_ComponentBoundEvent_51_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__WikiButton_K2Node_ComponentBoundEvent_52_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ESButton_K2Node_ComponentBoundEvent_53_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__CZButton_K2Node_ComponentBoundEvent_25_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ZHButton_K2Node_ComponentBoundEvent_61_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__RoButton_K2Node_ComponentBoundEvent_62_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__TWButton_K2Node_ComponentBoundEvent_63_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__KOButton_K2Node_ComponentBoundEvent_64_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__TwitterButton_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature();
    void Construct();
    void BndEvt__YTButton_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ItButton_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ModsButton_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__FutureUpdatesButton_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ARButton_K2Node_ComponentBoundEvent_27_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_MainMenu_ContinueButton_1_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature();
    void Destruct();
    void BndEvt__QuitPanelButton_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_MainMenu_UI_PlayerShelf_K2Node_ComponentBoundEvent_1_OnThumbnailSelected__DelegateSignature(class APlayerController* PlayerController, int32 SessionID, class UUI_PlayerThumbnail_C* Thumbnail);
    void BndEvt__UI_MainMenu_NewGameCancelButton_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_MainMenu_NewGameConfirmButton_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__DiscordButton_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__PatchNotesButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__NewGameButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_MainMenu_MerchButton_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SettingsPanelButton_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__CreditsButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_MainMenu_JAButton_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_MainMenu_InstagramButton_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_MainMenu_TikTokButton_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_MainMenu_NOButton_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_MainMenu_SVButton_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_MainMenu_DAButton_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature();
    void ExecuteUbergraph_UI_MainMenu(int32 EntryPoint);
};

#endif
